#version: '3.8'
#version: '3.3'

services:
  LLM4LOG: 
    image: llm4log:latest
    container_name: llm4log
    volumes:
      - ./:/app
      - ./data/pretrained_models:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1']
            capabilities: [gpu]
    tty: true
    command: "/bin/bash"
