
dataset:
  log_file: "data/Linux.txt"
model:
  PROJECT_ID : "log-analysis-433902"
  # LOCATION : "us-central1"
  LOCATION : "asia-east1"
  # LOCATION : "asia-east2"
  MODEL_NAME : "gemini-1.5-pro"
  temperature: 0.2
  top_p: 0.8
inference:
  save_path: "result"
  chunk_size: 192*1024
  count: False
test:
  llm_result_file: "result/result_2024-09-10_17-13-04_all file 192k-12 only extraction/inference_output/merged.json"
  re_result_file: "data/result-re_Linux.json"
  human_result_file: "data/human_evaluation.json"
comment: "all file 192k-12 extraction test"

